name: "Process stale issues and PRs"
on:
    schedule:
        - cron: 14 3 * * *
    workflow_dispatch:

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v6
              with:
                  stale-issue-message: "This issue has been marked as stale because of inactivity. Comment on this issue or it will be closed in 14 days."
                  days-before-stale: 14
                  days-before-close: 14
                  any-labels: "question,awaiting confirmation"
